const express = require('express')
const app = express()
const mongoose = require('mongoose')
const session = require('express-session')
var morgan = require('morgan')
const dotenv =require('dotenv')
const userUrls= require('./routes/userRoutes')
const adminUrls= require('./routes/adminRoutes')
const chatUrls= require('./routes/chatRoutes')
const messageUrls= require('./routes/messageRoutes')

morgan('tiny')
const cors = require('cors')
dotenv.config()
mongoose.connect(process.env.DATABASE_ACCESS ,()=>console.log("database connected"))
app.use(session({ secret: 'keyboard cat', cookie: { maxAge: 60000 },resave: true,saveUninitialized: true}))
app.use(express.json())
app.use(cors())

app.use('/api/',userUrls)
app.use('/api/admin',adminUrls)
app.use('/api/chat',chatUrls)
app.use('/api/message',messageUrls)

app.use('/api/images', express.static('public/Posts'))
app.use('/api/DP', express.static('public/DP'))

app.listen(4000,()=> console.log("server is running"))